# Generated by Django 3.2.8 on 2023-12-15 07:26

import cricket.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('coaching_experience', models.PositiveIntegerField()),
                ('specialized_in', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('batting_hand', models.CharField(max_length=20)),
                ('bowling_style', models.CharField(max_length=50)),
                ('player_image', models.ImageField(blank=True, null=True, upload_to=cricket.models.player_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Umpire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('experience_years', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.coach')),
                ('players', models.ManyToManyField(related_name='teams', to='cricket.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_of_team', to='cricket.team'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('toss_decision', models.CharField(blank=True, choices=[('bat', 'Decided to bat first'), ('bowl', 'Decided to bowl first')], max_length=4, null=True)),
                ('inning', models.IntegerField(blank=True, choices=[(1, 'First Inning'), (2, 'Second Inning')], default=1, null=True)),
                ('match_type', models.IntegerField(blank=True, choices=[(1, 'Day'), (2, 'Day and Night')], default=1, null=True)),
                ('batting_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batting_team_matches', to='cricket.team')),
                ('bowler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bowler_matches', to='cricket.player')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.location')),
                ('non_striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='non_striker_matches', to='cricket.player')),
                ('striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='striker_matches', to='cricket.player')),
                ('team1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='cricket.team')),
                ('team2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='cricket.team')),
                ('toss_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toss_winner', to='cricket.team')),
                ('umpire', models.ManyToManyField(blank=True, default=3, null=True, related_name='umpires', to='cricket.Umpire')),
            ],
        ),
        migrations.CreateModel(
            name='LiveScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('runs', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=0)),
                ('extras', models.CharField(choices=[('no_extra', 'NE'), ('wide', 'WD'), ('wide_run', 'WD + R'), ('byes', 'B'), ('leg_byes', 'LB'), ('no_ball', 'NB'), ('no_ball_runs', 'NB + R'), ('no_ball_byes', 'NB + B'), ('no_ball_lb', 'NB + LB'), ('penalty_runs', 'PR')], default='no_extra', max_length=20)),
                ('wicket', models.CharField(choices=[('not_out', 'NO'), ('bowled_out', 'B'), ('caught_out', 'C'), ('leg_before_wicket', 'LBW'), ('run_out', 'RO'), ('stumped_out', 'ST'), ('hit_wicket', 'HT WKT'), ('retired_out', 'RET'), ('timed_out', 'TO'), ('hit_the_ball_twice', 'HBT'), ('obstructing_the_field', 'OF'), ('retired_not_out', 'RET NO')], default='not_out', max_length=30)),
                ('wicket_at', models.CharField(blank=True, max_length=4, null=True, verbose_name='Wicket At')),
                ('run_at', models.CharField(blank=True, max_length=4, null=True, verbose_name='Run At')),
                ('partner', models.CharField(blank=True, max_length=4, null=True, verbose_name='Partner')),
                ('partner_data', models.CharField(blank=True, max_length=4, null=True, verbose_name='Partner Data')),
                ('bowler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricket.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.match')),
                ('non_strike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_strike_scores', to='cricket.player', verbose_name='Non-Strike Player')),
                ('out_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='out_scores', to='cricket.player', verbose_name='Out Player')),
                ('strike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strike_scores', to='cricket.player', verbose_name='Strike Player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricket.team')),
                ('wicket_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wicket_by_scores', to='cricket.player', verbose_name='Wicket By Player')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('match_format', models.CharField(choices=[('T20', 'T20'), ('ODI', 'ODI')], default='T20', max_length=3)),
                ('matches', models.ManyToManyField(blank=True, related_name='leagues', to='cricket.Match')),
            ],
        ),
    ]
