# Generated by Django 3.2.8 on 2023-12-15 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='umpire',
            name='match',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='cricket.match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='umpire',
            field=models.ManyToManyField(related_name='umpires', to='cricket.Umpire'),
        ),
    ]
