# Generated by Django 3.2.8 on 2023-12-15 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0003_alter_umpire_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umpire',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='cricket.match'),
        ),
    ]
