# Generated by Django 4.2 on 2023-12-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0004_alter_umpire_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_profile',
            field=models.TextField(blank=True),
        ),
    ]
