# Generated by Django 3.2.8 on 2023-12-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0005_team_team_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='first_inning_team',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
